spring:
  application:
    name: payment-bridge
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  h2:
    console:
      enabled: true
logging:
  level:
    com.payment.bridge: DEBUG
    org.springframework.web: DEBUG
